version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongodb_network

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    restart: always
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://rootuser:rootpass@mongodb:27017/PythonTry?authSource=admin
    depends_on:
      - mongodb
    networks:
      - mongodb_network

volumes:
  data: {}

networks:
  mongodb_network:
    driver: bridge